#t? ??ng ??ng b? (update) schema trong database d?a trên các entity trong code
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true

#ignore when push
spring.config.import=optional:application-secret.properties
